name = "drivers"
description = "Random peripheral drivers"
version = "0.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

[[depends-on]]
hal = "~0.3.0"
synack_misc = "~0.1.0"

[[pins]]
synack_misc = { url='https://github.com/JeremyGrosser/synack_misc' }
